# Configure this Discovery Server
eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: false  #telling the server not to register himself in the service registry
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
  

# HTTP (Tomcat) port
server:
  port: 8761  

spring:
  boot:
    admin:
      context-path: /admin  #A different context path for admin server has been provided not conflicting with eureka