#adding a namespace. this is optional, can be created from commandline also
apiVersion: v1
kind: Namespace
metadata:
  name: my-boot-apps
---
#PersistentVolumeClaim config File
#Please note below points
#Usage of hostPath is not recommended in production
#capacity of PV and PVC needs to match
#accessModes of PV and PVC needs to match
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mylogs-demo-pv
  namespace: my-boot-apps
spec:
  capacity:
    storage: 256Mi
#  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete #Retain
  storageClassName: manual #local-storage
#  local:
#Minikube supports only hostpath.
  hostPath: 
    path: /myK8storage/data/db  #this path will be available inside minikube vm and not on local machine
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mylogs-pvc
  namespace: my-boot-apps
spec:
#  volumeName: mylogs-demo-pv
  storageClassName: manual #local-storage
#  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: ConfigMap  # this config map is not used anywhere currently
metadata:
  name: mongo-config
  namespace: my-boot-apps
  labels:
    app: mongodbapp
data:
  mongo-url: mongodbapp
  host: mongodbapp
  database: BookStore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: my-boot-apps
  labels:
    app: mongodbapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodbapp
  template:
    metadata:
      labels:
        app: mongodbapp
      name: mongodbservice
#        selector: mongodb-standalone
    spec:
      containers:
      - name: mongodbapp
        imagePullPolicy: Never  #IfNotPresent
        image: mongo
        args: ["--dbpath","/myK8storage/data/db"]
#        env:
#          - name: MONGO_INITDB_ROOT_USERNAME
#            value: admin
#          - name: MONGO_INITDB_ROOT_PASSWORD
#            value: password
        ports:
        - containerPort: 27017
#        command: ["chmod -R 0777 /myK8storage/data/db"]
        volumeMounts:
            - name: storage
              mountPath: /myK8storage/data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mylogs-pvc        
---
apiVersion: v1
kind: Service
metadata:
  name: mongodbservice
  namespace: my-boot-apps
  labels:
    app: mongodbapp
spec:
  selector:
    app: mongodbapp
  ports:
  - protocol: TCP
    port: 27017  #could be anything, doesnt matter
    targetPort: 27017  #should be same as containerPort