#adding a namespace. this is optional, can be created from commandline also
apiVersion: v1
kind: Namespace
metadata:
  name: eks-sample-app
---
#PersistentVolumeClaim config File
#Please note below points
#Usage of hostPath is not recommended in production
#capacity of PV and PVC needs to match
#accessModes of PV and PVC needs to match
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mylogs-demo-pv
  namespace: eks-sample-app  
spec:
  capacity:
    storage: 256Mi
#  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual #local-storage
#  local:
#Minikube supports only hostpath.
  hostPath: 
    path: /home/vikasgond/storage  #this path will be available inside minikube vm and not on local machine
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mylogs-pvc
  namespace: eks-sample-app
spec:
#  volumeName: mylogs-demo-pv
  storageClassName: manual #local-storage
#  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boot-logback-deployment
  namespace: eks-sample-app
  labels:
    app: boot-logback-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boot-logback-app
  template:
    metadata:
      labels:
        app: boot-logback-app
    spec:
      containers:
      - name: boot-logback-app
        image: vikasuni/boot-logback-demo
        ports:
        - name: http
          containerPort: 8111
        imagePullPolicy: IfNotPresent
        env:
          - name: LOGFILE_PATH  # this variable is defined in application properties of the app
            value: /home/vikasgond/storage/myAppLogs/applog.log  #log file will be generated inside minikube vm and not on local machine
            #can be viewed by executing command: minikube ssh -- cat /home/vikasgond/storage/myAppLogs/applog.log
        volumeMounts:
            - name: storage
              mountPath: /home/vikasgond/storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mylogs-pvc
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: boot-logback-service
  namespace: eks-sample-app
  labels:
    app: boot-logback-app
spec:
  type: ClusterIP
  selector:
    app: boot-logback-app
  ports:
    - protocol: TCP
      port: 8111
      targetPort: 8111
---
apiVersion: v1
kind: Service
metadata:
  name: boot-logback-nodeport
  namespace: eks-sample-app
  labels:
    app: boot-logback-app
spec:
  type: NodePort
  selector:
    app: boot-logback-app
  ports:
    - protocol: TCP
      port: 8111
      targetPort: 8111
---
apiVersion: v1
kind: Service
metadata:
  name: boot-logback-loadbalancer
  namespace: eks-sample-app
spec:
  type: LoadBalancer
  selector:
    app: boot-logback-app
  ports:
    - protocol: TCP
      port: 8111
      targetPort: 8111