apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-java-deployment
  namespace: eks-sample-app
  labels:
    app: my-java-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-java-app
  template:
    metadata:
      labels:
        app: my-java-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: my-java-app
        image: vikasuni007/java-api-vik
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
---
apiVersion: v1
kind: Service
metadata:
  name: my-java-service
  namespace: eks-sample-app
  labels:
    app: my-java-app
spec:
  type: ClusterIP
  selector:
    app: my-java-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-java-nodeport
  namespace: eks-sample-app
  labels:
    app: my-java-app
spec:
  type: NodePort
  selector:
    app: my-java-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-java-loadbalancer
  namespace: eks-sample-app
spec:
  type: LoadBalancer
  selector:
    app: my-java-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080