server:
  port: 8121

#spring:
#  datasource:
#    url: jdbc:mysql://localhost/mytestOauth?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
#    username: root
#    password: root@123
#    driver-class-name: com.mysql.jdbc.Driver
    
#spring.jpa.hibernate.ddl-auto=update

#  jpa:
#    hibernate:
#      #ddl-auto: create-drop
#      ddl-auto: update
#    show-sql: true
