server:
  port: 8111

spring:
  datasource:
    url: jdbc:mysql://localhost/mytestOauth?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: root
    password: root@123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      #ddl-auto: create-drop
      #ddl-auto: create
      ddl-auto: update
    show-sql: true
    
logging:
  level:
    org.springframework.security: DEBUG