# using configuration below, 
#the employee-service is accessible at- http://localhost:8079/api/demo/findEmployeeDetails/111
#zuul.routes.findEmployeeDetails.path: /api/demo/**
#zuul.routes.findEmployeeDetails.url: http://localhost:8011


# using configuration below, 
#the employee-service is accessible at- http://localhost:8079/employee-service/findEmployeeDetails/111
eureka.instance.preferIpAddress: true
eureka.client.registerWithEureka: true
eureka.client.fetchRegistry: true

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka

server.port: 8079
spring.application.name: employee-zuul-service

#to enable actuator endpoints, disabling authentication is necessary
management.security.enabled: false

#this is added to prevent timeout exception for long requests- https://www.appsdeveloperblog.com/zuul-api-gateway-timeout-error/
ribbon.ReadTimeout: 60000