#the employee-service is accessible at- http://localhost:8079/api/demo/findEmployeeDetails/111

zuul.routes.findEmployeeDetails.path: /api/demo/**
zuul.routes.findEmployeeDetails.url: http://localhost:8011
eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka
server.port: 8079

spring.application.name: employee-zuul-service