server:
  port: 8010    #port number
  context-path: /emp-api-gateway
 
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
spring:    
  application:
    name: api-gateway   
     
management:
  security:
    enabled: false  
 
logging:
  level:
    com.self.sprintboot.learning.apigateway: DEBUG

#we'll find our security filters by enabling the logging for the FilterChainProxy.
#We can enable logging by adding the following line to application.properties:
logging.level.org.springframework.security.web.FilterChainProxy: DEBUG

logging.level.org.springframework.security.web.authentication.www.BasicAuthenticationFilter: DEBUG

logging.level.org.springframework.security.authentication.ProviderManager: DEBUG
    
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 100000

ribbon.ReadTimeout: 100000

ribbon.ConnectTimeout: 100000