server:
  port: 8011    
 
eureka:         
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
 
spring:    
  application:
    name: employee-service   
     
management:
  security:
    enabled: false  
 
#to add custom logger config, comment below lines 
#logging:
#  level:
 #   com.self.sprintboot.learning.employee: INFO
#  pattern:
#    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
#    file: "%d %p %c{1.} [%t] %m%n"
#  file: app.log