server:
  port: 9200
spring:
  kafka:
    consumer:
#      bootstrap-servers: computer-VirtualBox:9092    # this works with kafka running in virtualbox
#      bootstrap-servers: "localhost:9092"  #this works with kafka running in docker in wsl
#      bootstrap-servers: "localhost:9093"  #this works with kafka running in WSL
      bootstrap-servers: "[::1]:9092"  #this works with kafka running in WSL
      group-id: group1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
#      bootstrap-servers: computer-VirtualBox:9092
      bootstrap-servers: "[::1]:9092"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer